spring:
    application:
      name : GATE-WAY
server:
   port: 9898
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
zuul:
  ignored-services: '*'
  routes:
    testing-app: /test/**
ribbon:
    eureka:
      enabled:true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/